Create database ASM_SOF3021
Go
USE ASM_SOF3021
GO
-- Role
CREATE TABLE Role(
Id INT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL
)
GO
-- User
CREATE TABLE [User](
Id INT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
MatKhau VARCHAR(MAX) DEFAULT NULL,
IdRole INT,
Email NVARCHAR(100) NOT NULL,
TrangThai INT DEFAULT 0  --0:active, 1:not active
)
GO
--HoaDon
CREATE TABLE HoaDon(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdUser INT,
TinhTrang NVARCHAR(30) Null,
NgayTao DATE DEFAULT NULL,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
)
GO
--GioHang
CREATE TABLE GioHang(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdUser INT,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
TinhTrang NVARCHAR(30) Null
)
GO
-- Tu Lanh
CREATE TABLE TuLanh(
Id INT IDENTITY(1,1) PRIMARY KEY,
Ten NVARCHAR(50) NOT NULL,
DungTich int NULL,
SoLuongTon INT,
SoCanhCua INT,
DonGia DECIMAL(20,0) DEFAULT 0,
)

GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
Id int identity,
IdHoaDon INT,
IdTuLanh INT,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (IdHoaDon,IdTuLanh),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id),
CONSTRAINT FK2 FOREIGN KEY(IdTuLanh) REFERENCES TuLanh(Id),
)
GO
CREATE TABLE GioHangChiTiet(
Id int identity,
IdGioHang INT,
IdTuLanh INT,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
DonGiaKhiGiam DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_GioHangCT PRIMARY KEY (IdGioHang,IdTuLanh),
CONSTRAINT FK1_IdGioHang FOREIGN KEY(IdGioHang) REFERENCES GioHang(Id),
CONSTRAINT FK2_IdTuLanh FOREIGN KEY(IdTuLanh) REFERENCES TuLanh(Id),
)
GO
--T?O QUAN H? GI?A CÁC B?NG
--User - Role
ALTER TABLE [User] ADD FOREIGN KEY (IdRole) REFERENCES Role(Id)
-- HoaDon - User
ALTER TABLE HoaDon ADD FOREIGN KEY (IdUser) REFERENCES [User](Id)
-- GioHang - User
ALTER TABLE GioHang ADD FOREIGN KEY (IdUser) REFERENCES [User](Id)


Go
INSERT INTO Role(Ma, Ten)
	VALUES('CV2', 'USER'),
		('CV1', 'ADMIN')

