Create database ASM_SOF3021
Go
USE ASM_SOF3021
GO
-- Role
CREATE TABLE Role(
Id INT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL
)
GO
-- User
CREATE TABLE [User](
Id INT IDENTITY(1,1) PRIMARY KEY,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
MatKhau VARCHAR(MAX) DEFAULT NULL,
Email NVARCHAR(100) NOT NULL,
IdRole INT,
TrangThai INT DEFAULT 0  --0:active, 1:not active
)
GO

--HoaDon
CREATE TABLE HoaDon(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdUser INT,
Ma VARCHAR(20) UNIQUE,
TinhTrang NVARCHAR DEFAULT Null,
NgayTao DATE DEFAULT NULL,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,

)
GO
--GioHang
CREATE TABLE GioHang(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdUser INT,
Ma VARCHAR(20) UNIQUE,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
TinhTrang NVARCHAR DEFAULT Null
)
GO
-- TaiNGhe
CREATE TABLE TaiNghe(
Id INT IDENTITY(1,1) PRIMARY KEY,
TenTaiNghe NVARCHAR(50) NOT NULL,
CongKetNoi NVARCHAR(50) NOT NULL,
SoLuongTon INT,
TanSo INT,
KichThuocMangLoa FLOAT,
DonGia DECIMAL(20,0) DEFAULT 0,
)

GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdHoaDon INT,
IdTaiNghe INT,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id),
CONSTRAINT FK2 FOREIGN KEY(IdTaiNghe) REFERENCES TaiNghe(Id),
)
GO
CREATE TABLE GioHangChiTiet(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdGioHang INT,
IdTaiNghe INT,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT FK1_IdGioHang FOREIGN KEY(IdGioHang) REFERENCES GioHang(Id),
CONSTRAINT FK2_IdTaiNghe FOREIGN KEY(IdTaiNghe) REFERENCES TaiNghe(Id),
)
GO

--TẠO QUAN HỆ GIỮA CÁC BẢNG
-- Role - User
ALTER TABLE [User] ADD FOREIGN KEY (IdRole) REFERENCES Role(Id)
-- HoaDon - User
ALTER TABLE HoaDon ADD FOREIGN KEY (IdUser) REFERENCES [User](Id)
-- GioHang - User
ALTER TABLE GioHang ADD FOREIGN KEY (IdUser) REFERENCES [User](Id)
--
Go
INSERT INTO Role(Ma, Ten)
	VALUES(1, 'User'),
		(2, 'Admin')

INSERT INTO [User](Ma,Ten,DiaChi,GioiTinh,Email,NgaySinh,MatKhau,TrangThai,IdRole)
	VALUES('U1', 'Nguyen Van Hieu', 'HN', 'Nam', 'user1@gmail.com', '2003-01-08', '123456', 0, 1),
		('U2', 'User @@@', 'HN', 'Nam', 'user2@gmail.com', '2005-11-08', '123456', 0, 1),
		('A1', 'Nguyen Dang Hieu', 'HN', 'Nam', 'admin@gmail.com', '2003-12-14', '123456', 0, 2)